<?php
require __DIR__ . '/../src/session.php';
if (!isset($_SESSION["admin_id"])) { echo "Unauthorized"; exit; }
require_once __DIR__ . '/../src/db.php';

// Ensure the doctor_accounts table exists
$conn->query("CREATE TABLE IF NOT EXISTS doctor_accounts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id  INTEGER NOT NULL UNIQUE REFERENCES doctors(id) ON DELETE CASCADE,
    username   VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");

require_once __DIR__ . '/test_procedures_schema.php';
test_procedures_ensure($conn);

function save_doctor_procedures($conn, $doctor_id, $raw_json)
{
    if ($doctor_id <= 0) return true;
    $items = json_decode((string)$raw_json, true);
    if (!is_array($items)) return true;

    $del = $conn->prepare("DELETE FROM doctor_test_procedures WHERE doctor_id = ?");
    $del->bind_param("i", $doctor_id);
    $del->execute();
    $del->close();

    $ok = true;
    foreach ($items as $it) {
        if (!is_array($it)) continue;
        $name = isset($it['name']) ? trim((string)$it['name']) : '';
        if ($name === '' || strlen($name) > 140) continue;
        $pid = isset($it['id']) ? (int)$it['id'] : 0;

        if ($pid > 0) {
            $chk = $conn->prepare("SELECT id FROM test_procedures WHERE id = ?");
            $chk->bind_param("i", $pid);
            $chk->execute();
            $chk->store_result();
            if ($chk->num_rows === 0) $pid = 0;
            $chk->close();
        }

        if ($pid <= 0) {
            $sel = $conn->prepare("SELECT id FROM test_procedures WHERE name = ?");
            $sel->bind_param("s", $name);
            $sel->execute();
            $sel->store_result();
            if ($sel->num_rows > 0) {
                $sel->bind_result($fid);
                $sel->fetch();
                $pid = (int)$fid;
            } else {
                $ins = $conn->prepare("INSERT INTO test_procedures (name) VALUES (?)");
                $ins->bind_param("s", $name);
                if ($ins->execute()) {
                    $pid = (int)$ins->insert_id;
                    if ($pid <= 0) {
                        $back = $conn->prepare("SELECT id FROM test_procedures WHERE name = ?");
                        $back->bind_param("s", $name);
                        $back->execute();
                        $back->store_result();
                        if ($back->num_rows > 0) { $back->bind_result($bid); $back->fetch(); $pid = (int)$bid; }
                        $back->close();
                    }
                } else {
                    $sel2 = $conn->prepare("SELECT id FROM test_procedures WHERE name = ?");
                    $sel2->bind_param("s", $name);
                    $sel2->execute();
                    $sel2->store_result();
                    if ($sel2->num_rows > 0) {
                        $sel2->bind_result($fid2);
                        $sel2->fetch();
                        $pid = (int)$fid2;
                    } else {
                        $ok = false;
                    }
                    $sel2->close();
                }
                $ins->close();
            }
            $sel->close();
        }

        if ($pid > 0) {
            $link = $conn->prepare("INSERT INTO doctor_test_procedures (doctor_id, procedure_id) VALUES (?, ?)");
            $link->bind_param("ii", $doctor_id, $pid);
            if (!$link->execute()) $ok = false;
            $link->close();
        }
    }
    return $ok;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') { echo "Invalid request"; exit; }

$action = isset($_POST['action']) ? trim($_POST['action']) : '';

if ($action === 'add') {
    $name       = isset($_POST['name'])       ? trim($_POST['name'])       : '';
    $specialty  = isset($_POST['specialty'])  ? trim($_POST['specialty'])  : '';
    $schedule   = isset($_POST['schedule'])   ? trim($_POST['schedule'])   : '';
    $experience = isset($_POST['experience']) ? (int)$_POST['experience']  : 0;

    if (empty($name) || empty($specialty) || empty($schedule)) {
        echo "All fields are required"; exit;
    }

    $stmt = $conn->prepare("INSERT INTO doctors (name, specialty, schedule, experience) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("sssi", $name, $specialty, $schedule, $experience);
    $ok = $stmt->execute();
    $doctor_id = (int)$stmt->insert_id;
    $stmt->close();

    if (!$ok) { echo "Failed: " . $stmt->error; exit; }

    if ($doctor_id <= 0) {
        $fb = $conn->prepare("SELECT id FROM doctors WHERE name = ? AND specialty = ? AND schedule = ? ORDER BY id DESC LIMIT 1");
        $fb->bind_param("sss", $name, $specialty, $schedule);
        $fb->execute();
        $fb->store_result();
        if ($fb->num_rows > 0) { $fb->bind_result($fbid); $fb->fetch(); $doctor_id = (int)$fbid; }
        $fb->close();
    }

    $procsJson = isset($_POST['test_procedures_json']) ? $_POST['test_procedures_json'] : '';
    save_doctor_procedures($conn, $doctor_id, $procsJson);
    echo "success";
    $conn->close();
    exit;

} elseif ($action === 'edit') {
    $id         = isset($_POST['doctor_id'])  ? (int)$_POST['doctor_id']   : 0;
    $name       = isset($_POST['name'])       ? trim($_POST['name'])       : '';
    $specialty  = isset($_POST['specialty'])  ? trim($_POST['specialty'])  : '';
    $schedule   = isset($_POST['schedule'])   ? trim($_POST['schedule'])   : '';
    $experience = isset($_POST['experience']) ? (int)$_POST['experience']  : 0;

    if (!$id || empty($name) || empty($specialty) || empty($schedule)) {
        echo "All fields are required"; exit;
    }

    $stmt = $conn->prepare("UPDATE doctors SET name=?, specialty=?, schedule=?, experience=? WHERE id=?");
    $stmt->bind_param("sssii", $name, $specialty, $schedule, $experience, $id);

    if (!$stmt->execute()) { echo "Failed: " . $stmt->error; $stmt->close(); $conn->close(); exit; }
    $stmt->close();

    $procsJson = isset($_POST['test_procedures_json']) ? $_POST['test_procedures_json'] : '';
    save_doctor_procedures($conn, $id, $procsJson);
    echo "success";
    $conn->close();
    exit;

} elseif ($action === 'delete') {
    $id = isset($_POST['doctor_id']) ? (int)$_POST['doctor_id'] : 0;

    if (!$id) { echo "Invalid doctor ID"; exit; }

    $stmt = $conn->prepare("DELETE FROM doctors WHERE id=?");
    $stmt->bind_param("i", $id);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} elseif ($action === 'add_account') {
    $doctor_id = isset($_POST['doctor_id']) ? (int)$_POST['doctor_id'] : 0;
    $username  = isset($_POST['username'])  ? trim($_POST['username'])  : '';
    $password  = isset($_POST['password'])  ? $_POST['password']        : '';

    if (!$doctor_id) { echo "Please select a doctor"; exit; }
    if (!preg_match('/^[a-zA-Z0-9_]{3,30}$/', $username)) {
        echo "Username must be 3-30 characters (letters, numbers, underscore only)";
        exit;
    }
    if (strlen($password) < 8) { echo "Password must be at least 8 characters"; exit; }

    $check = $conn->prepare("SELECT id FROM doctors WHERE id = ?");
    $check->bind_param("i", $doctor_id);
    $check->execute();
    $check->store_result();
    if ($check->num_rows === 0) { $check->close(); echo "Doctor not found"; exit; }
    $check->close();

    $check = $conn->prepare("SELECT id FROM doctor_accounts WHERE doctor_id = ?");
    $check->bind_param("i", $doctor_id);
    $check->execute();
    $check->store_result();
    if ($check->num_rows > 0) { $check->close(); echo "This doctor already has an account"; exit; }
    $check->close();

    $exists = $conn->prepare("SELECT id FROM doctor_accounts WHERE username = ?");
    $exists->bind_param("s", $username);
    $exists->execute();
    $exists->store_result();
    if ($exists->num_rows > 0) { $exists->close(); echo "Username already taken"; exit; }
    $exists->close();

    $hashed = password_hash($password, PASSWORD_DEFAULT);
    $stmt = $conn->prepare("INSERT INTO doctor_accounts (doctor_id, username, password) VALUES (?, ?, ?)");
    $stmt->bind_param("iss", $doctor_id, $username, $hashed);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} elseif ($action === 'reset_account') {
    $account_id = isset($_POST['account_id']) ? (int)$_POST['account_id'] : 0;
    $password   = isset($_POST['password'])   ? $_POST['password']        : '';

    if (!$account_id) { echo "Invalid account"; exit; }
    if (strlen($password) < 8) { echo "Password must be at least 8 characters"; exit; }

    $hashed = password_hash($password, PASSWORD_DEFAULT);
    $stmt = $conn->prepare("UPDATE doctor_accounts SET password = ? WHERE id = ?");
    $stmt->bind_param("si", $hashed, $account_id);
    if ($stmt->execute() && $stmt->affected_rows > 0) { $stmt->close(); echo "success"; exit; }
    $stmt->close();
    echo "Failed to reset password. Please try again.";

} elseif ($action === 'delete_account') {
    $account_id = isset($_POST['account_id']) ? (int)$_POST['account_id'] : 0;

    if (!$account_id) { echo "Invalid account"; exit; }

    $stmt = $conn->prepare("DELETE FROM doctor_accounts WHERE id = ?");
    $stmt->bind_param("i", $account_id);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} else {
    echo "Unknown action";
}

$conn->close();
?>