<?php
require __DIR__ . '/../src/session.php';
if (!isset($_SESSION["admin_id"])) { echo "Unauthorized"; exit; }
require_once __DIR__ . '/../src/db.php';

// Ensure the doctor_accounts table exists
$conn->query("CREATE TABLE IF NOT EXISTS doctor_accounts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id  INTEGER NOT NULL UNIQUE REFERENCES doctors(id) ON DELETE CASCADE,
    username   VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");

if ($_SERVER['REQUEST_METHOD'] !== 'POST') { echo "Invalid request"; exit; }

$action = isset($_POST['action']) ? trim($_POST['action']) : '';

if ($action === 'add') {
    $name       = isset($_POST['name'])       ? trim($_POST['name'])       : '';
    $specialty  = isset($_POST['specialty'])  ? trim($_POST['specialty'])  : '';
    $schedule   = isset($_POST['schedule'])   ? trim($_POST['schedule'])   : '';
    $experience = isset($_POST['experience']) ? (int)$_POST['experience']  : 0;

    if (empty($name) || empty($specialty) || empty($schedule)) {
        echo "All fields are required"; exit;
    }

    $stmt = $conn->prepare("INSERT INTO doctors (name, specialty, schedule, experience) VALUES (?, ?, ?, ?)");
    $stmt->bind_param("sssi", $name, $specialty, $schedule, $experience);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} elseif ($action === 'edit') {
    $id         = isset($_POST['doctor_id'])  ? (int)$_POST['doctor_id']   : 0;
    $name       = isset($_POST['name'])       ? trim($_POST['name'])       : '';
    $specialty  = isset($_POST['specialty'])  ? trim($_POST['specialty'])  : '';
    $schedule   = isset($_POST['schedule'])   ? trim($_POST['schedule'])   : '';
    $experience = isset($_POST['experience']) ? (int)$_POST['experience']  : 0;

    if (!$id || empty($name) || empty($specialty) || empty($schedule)) {
        echo "All fields are required"; exit;
    }

    $stmt = $conn->prepare("UPDATE doctors SET name=?, specialty=?, schedule=?, experience=? WHERE id=?");
    $stmt->bind_param("sssii", $name, $specialty, $schedule, $experience, $id);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} elseif ($action === 'delete') {
    $id = isset($_POST['doctor_id']) ? (int)$_POST['doctor_id'] : 0;

    if (!$id) { echo "Invalid doctor ID"; exit; }

    $stmt = $conn->prepare("DELETE FROM doctors WHERE id=?");
    $stmt->bind_param("i", $id);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} elseif ($action === 'add_account') {
    $doctor_id = isset($_POST['doctor_id']) ? (int)$_POST['doctor_id'] : 0;
    $username  = isset($_POST['username'])  ? trim($_POST['username'])  : '';
    $password  = isset($_POST['password'])  ? $_POST['password']        : '';

    if (!$doctor_id) { echo "Please select a doctor"; exit; }
    if (!preg_match('/^[a-zA-Z0-9_]{3,30}$/', $username)) {
        echo "Username must be 3-30 characters (letters, numbers, underscore only)";
        exit;
    }
    if (strlen($password) < 8) { echo "Password must be at least 8 characters"; exit; }

    $check = $conn->prepare("SELECT id FROM doctors WHERE id = ?");
    $check->bind_param("i", $doctor_id);
    $check->execute();
    $check->store_result();
    if ($check->num_rows === 0) { $check->close(); echo "Doctor not found"; exit; }
    $check->close();

    $check = $conn->prepare("SELECT id FROM doctor_accounts WHERE doctor_id = ?");
    $check->bind_param("i", $doctor_id);
    $check->execute();
    $check->store_result();
    if ($check->num_rows > 0) { $check->close(); echo "This doctor already has an account"; exit; }
    $check->close();

    $exists = $conn->prepare("SELECT id FROM doctor_accounts WHERE username = ?");
    $exists->bind_param("s", $username);
    $exists->execute();
    $exists->store_result();
    if ($exists->num_rows > 0) { $exists->close(); echo "Username already taken"; exit; }
    $exists->close();

    $hashed = password_hash($password, PASSWORD_DEFAULT);
    $stmt = $conn->prepare("INSERT INTO doctor_accounts (doctor_id, username, password) VALUES (?, ?, ?)");
    $stmt->bind_param("iss", $doctor_id, $username, $hashed);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} elseif ($action === 'reset_account') {
    $account_id = isset($_POST['account_id']) ? (int)$_POST['account_id'] : 0;
    $password   = isset($_POST['password'])   ? $_POST['password']        : '';

    if (!$account_id) { echo "Invalid account"; exit; }
    if (strlen($password) < 8) { echo "Password must be at least 8 characters"; exit; }

    $hashed = password_hash($password, PASSWORD_DEFAULT);
    $stmt = $conn->prepare("UPDATE doctor_accounts SET password = ? WHERE id = ?");
    $stmt->bind_param("si", $hashed, $account_id);
    if ($stmt->execute() && $stmt->affected_rows > 0) { $stmt->close(); echo "success"; exit; }
    $stmt->close();
    echo "Failed to reset password. Please try again.";

} elseif ($action === 'delete_account') {
    $account_id = isset($_POST['account_id']) ? (int)$_POST['account_id'] : 0;

    if (!$account_id) { echo "Invalid account"; exit; }

    $stmt = $conn->prepare("DELETE FROM doctor_accounts WHERE id = ?");
    $stmt->bind_param("i", $account_id);
    echo $stmt->execute() ? "success" : "Failed: " . $stmt->error;
    $stmt->close();

} else {
    echo "Unknown action";
}

$conn->close();
?>