<?php
require __DIR__ . '/../src/session.php';
include __DIR__ . '/../src/db.php';

// Ensure the doctor_accounts table exists
$conn->query("CREATE TABLE IF NOT EXISTS doctor_accounts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id  INTEGER NOT NULL UNIQUE REFERENCES doctors(id) ON DELETE CASCADE,
    username   VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");

header('Content-Type: text/plain; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo "Invalid request";
    exit;
}

$username = isset($_POST['username']) ? trim($_POST['username']) : '';
$password = isset($_POST['password']) ? $_POST['password'] : '';

if (empty($username) || empty($password)) {
    echo "Username and password are required";
    exit;
}

$stmt = $conn->prepare(
    "SELECT da.id, da.doctor_id, da.password, d.name
     FROM doctor_accounts da
     JOIN doctors d ON da.doctor_id = d.id
     WHERE da.username = ?"
);
$stmt->bind_param("s", $username);
$stmt->execute();
$stmt->store_result();

if ($stmt->num_rows === 0) {
    $stmt->close();
    echo "Invalid username or password";
    $conn->close();
    exit;
}

$stmt->bind_result($account_id, $doctor_id, $hashed_password, $doctor_name);
$stmt->fetch();
$stmt->close();

if (password_verify($password, $hashed_password)) {
    $_SESSION['doctor_account_id'] = $account_id;
    $_SESSION['doctor_id']         = $doctor_id;
    $_SESSION['doctor_name']       = $doctor_name;
    $_SESSION['doctor_username']   = $username;
    echo "success";
} else {
    echo "Invalid username or password";
}

$conn->close();
?>