<?php
function test_procedures_ensure($conn)
{
    static $checked = false;
    if ($checked) return;
    $checked = true;
    @$conn->query("CREATE TABLE IF NOT EXISTS test_procedures (
        id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(140) NOT NULL
    )");
    @$conn->query("CREATE UNIQUE INDEX IF NOT EXISTS uq_test_procedures_name ON test_procedures (name)");
    @$conn->query("CREATE TABLE IF NOT EXISTS doctor_test_procedures (
        doctor_id    INTEGER NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
        procedure_id INTEGER NOT NULL REFERENCES test_procedures(id) ON DELETE CASCADE,
        PRIMARY KEY (doctor_id, procedure_id)
    )");

    $r = $conn->query("SELECT COUNT(*) AS c FROM test_procedures");
    if ($r && (int)$r->fetch_assoc()['c'] === 0) {
        $seed = [
            'Fertility Consultation',
            'Preconception Checkup',
            'Hormonal Panel',
            'Transvaginal Ultrasound',
            'Pelvic Ultrasound',
            'Complete Blood Count (CBC)',
            'Pregnancy Test (Serum hCG)',
            'Pap Smear',
            'Fetal Anomaly Scan',
            'Non-Stress Test (NST)',
            'Amniotic Fluid Index (AFI)',
            'Glucose Tolerance Test (GTT)',
            'Thyroid Function Test',
            'STI Screening',
            'Urinalysis',
        ];
        $stmt = $conn->prepare("INSERT INTO test_procedures (name) VALUES (?)");
        if ($stmt) {
            foreach ($seed as $s) {
                $stmt->bind_param("s", $s);
                @$stmt->execute();
            }
            $stmt->close();
        }
    }
}