<?php
/* Shared staff authentication used by the unified Sign In (login.php)
   and by the portal login pages (admin_login_process.php /
   doctor_login_process.php) so the rules live in exactly one place. */

function ensure_doctor_accounts_table($conn)
{
    $conn->query("CREATE TABLE IF NOT EXISTS doctor_accounts (
        id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        doctor_id  INTEGER NOT NULL UNIQUE REFERENCES doctors(id) ON DELETE CASCADE,
        username   VARCHAR(100) UNIQUE NOT NULL,
        password   VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )");
}

/**
 * Verify an admin account.
 *
 * @return array{ok: bool, found: bool, must_change: int, msg: string}
 *   found=false means no such admin username (caller may try another role).
 *   On ok=true the admin session variables are already set.
 */
function verify_admin_login($conn, $username, $password)
{
    $res = array('ok' => false, 'found' => false, 'must_change' => 0, 'msg' => 'Invalid username or password');

    // Fetch the account by username only (never compare raw password in SQL)
    $stmt = $conn->prepare("SELECT id, password, full_name, must_change_password, failed_attempts, locked_until FROM admin_users WHERE username = ?");
    $stmt->bind_param("s", $username);
    $stmt->execute();
    $stmt->store_result();

    if ($stmt->num_rows === 0) {
        $stmt->close();
        return $res;
    }

    $res['found'] = true;

    $stmt->bind_result($id, $stored, $full_name, $must_change, $failed_attempts, $locked_until);
    $stmt->fetch();
    $stmt->close();

    // Lockout check
    if (!empty($locked_until)) {
        $lock = new DateTime($locked_until);
        $now  = new DateTime();
        if ($lock > $now) {
            $mins = (int)ceil(($lock->getTimestamp() - $now->getTimestamp()) / 60);
            $res['msg'] = "Too many failed attempts. Account locked. Try again in about $mins minute(s).";
            return $res;
        }
        // Lock expired -> reset counters
        $conn->query("UPDATE admin_users SET failed_attempts = 0, locked_until = NULL WHERE id = $id");
        $failed_attempts = 0;
    }

    // Verify: bcrypt hash (new) or legacy plaintext (old accounts, upgrade on success)
    $isHash = preg_match('/^\$2[aby]\$/', $stored) === 1;
    if ($isHash) {
        $valid = password_verify($password, $stored);
    } else {
        $valid = hash_equals($stored, $password);
    }

    if (!$valid) {
        $failed_attempts++;
        if ($failed_attempts >= 5) {
            $conn->query("UPDATE admin_users SET failed_attempts = 0, locked_until = NOW() + INTERVAL '15 minutes' WHERE id = $id");
            $res['msg'] = "Too many failed attempts. Account locked for 15 minutes.";
        } else {
            $conn->query("UPDATE admin_users SET failed_attempts = $failed_attempts WHERE id = $id");
            $remaining = 5 - $failed_attempts;
            $res['msg'] = "Invalid username or password. $remaining attempt(s) remaining before lockout.";
        }
        return $res;
    }

    // Success -> reset counters
    $conn->query("UPDATE admin_users SET failed_attempts = 0, locked_until = NULL WHERE id = $id");

    // Legacy plaintext found in the DB -> hash it now and force a change (it was exposed)
    if (!$isHash) {
        $hash = password_hash($password, PASSWORD_DEFAULT);
        $upd  = $conn->prepare("UPDATE admin_users SET password = ?, must_change_password = 1 WHERE id = ?");
        $upd->bind_param("si", $hash, $id);
        $upd->execute();
        $upd->close();
        $must_change = 1;
    }

    $_SESSION['admin_id']          = $id;
    $_SESSION['admin_name']        = $full_name;
    $_SESSION['admin_username']    = $username;
    $_SESSION['admin_must_change'] = $must_change ? 1 : 0;

    $res['ok']          = true;
    $res['must_change'] = $must_change ? 1 : 0;
    $res['msg']         = $must_change ? 'change_password' : 'success';
    return $res;
}

/**
 * Verify a doctor account.
 *
 * @return array{ok: bool, found: bool, msg: string}
 *   On ok=true the doctor session variables are already set.
 */
function verify_doctor_login($conn, $username, $password)
{
    $res = array('ok' => false, 'found' => false, 'msg' => 'Invalid username or password');

    ensure_doctor_accounts_table($conn);

    $stmt = $conn->prepare(
        "SELECT da.id, da.doctor_id, da.password, d.name
         FROM doctor_accounts da
         JOIN doctors d ON da.doctor_id = d.id
         WHERE da.username = ?"
    );
    $stmt->bind_param("s", $username);
    $stmt->execute();
    $stmt->store_result();

    if ($stmt->num_rows === 0) {
        $stmt->close();
        return $res;
    }

    $res['found'] = true;

    $stmt->bind_result($account_id, $doctor_id, $hashed_password, $doctor_name);
    $stmt->fetch();
    $stmt->close();

    if (!password_verify($password, $hashed_password)) {
        return $res;
    }

    $_SESSION['doctor_account_id'] = $account_id;
    $_SESSION['doctor_id']         = $doctor_id;
    $_SESSION['doctor_name']       = $doctor_name;
    $_SESSION['doctor_username']   = $username;

    $res['ok']  = true;
    $res['msg'] = 'success';
    return $res;
}
