<?php
require __DIR__ . '/../toddcare-backend/src/session.php';
if (!isset($_SESSION["admin_id"])) { header("Location: admin_login.php"); exit; }
include __DIR__ . '/../toddcare-backend/src/db.php';
$admin_name = $_SESSION["admin_name"];

// Ensure the doctor_accounts table exists
$conn->query("CREATE TABLE IF NOT EXISTS doctor_accounts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id  INTEGER NOT NULL UNIQUE REFERENCES doctors(id) ON DELETE CASCADE,
    username   VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");

$doctors = $conn->query("SELECT d.id, d.name, d.specialty, d.schedule, d.experience, d.created_at, COUNT(a.id) as appointment_count FROM doctors d LEFT JOIN appointments a ON d.id=a.doctor_id GROUP BY d.id, d.name, d.specialty, d.schedule, d.experience, d.created_at ORDER BY d.name");
$accounts = $conn->query("SELECT da.id AS account_id, da.username, da.created_at, d.id AS doctor_id, d.name AS doctor_name, d.specialty FROM doctor_accounts da JOIN doctors d ON da.doctor_id=d.id ORDER BY d.name");
$doctors_options = $conn->query("SELECT id, name, specialty FROM doctors ORDER BY name");
$conn->close();
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <meta name="theme-color" content="#16a34a">
    <link rel="icon" href="images/Lustre.png" type="image/png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@500;600;700&family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">
    <script>try{if(localStorage.getItem('meTheme')==='dark'){document.documentElement.setAttribute('data-theme','dark');}}catch(e){}</script>
<link rel="stylesheet" href="admin.css?v=<?= filemtime(__DIR__ . '/../admin.css') ?>">
    <title>Doctor Management - LustreMDC Admin</title>
</head>
<body>
    <div class="sidebar-overlay" id="sidebarOverlay" onclick="closeSidebar()"></div>
    <div class="admin-layout">
    <aside class="admin-sidebar" id="adminSidebar">
        <div class="sidebar-brand">
            <span class="brand-icon"><img src="images/Lustre.png" alt="LustreMDC Logo" width="42" height="42" /></span>
            <span class="brand-text"><span>Admin</span></span>
        </div>
        <div class="sidebar-user">
            <div class="avatar avatar--sm"><?php echo strtoupper(substr(trim($admin_name),0,1)); ?></div>
            <div class="sidebar-user-body"><div class="sidebar-user-label">Logged in as</div><div class="sidebar-user-name"><?php echo htmlspecialchars($admin_name); ?></div></div>
        </div>
        <nav class="sidebar-nav">
            <a href="admin_dashboard.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg></span><span class="rail-label">Dashboard</span></a>
            <a href="admin_appointments.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="17" rx="3"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/><line x1="9" y1="15" x2="15" y2="15"/></svg></span><span class="rail-label">Appointments</span></a>
            <a href="admin_patients.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></span><span class="rail-label">Patients</span></a>
                <a href="admin_walkins.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.6 4.7L18 9.3l-4.4 1.6L12 15.6l-1.6-4.7L6 9.3l4.4-1.6z" style="stroke-width:1.8"/><path d="M5 20h14"/></svg></span><span class="rail-label">Walk-ins</span></a>
            <a href="admin_doctors.php" class="nav-item active"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" y1="8" x2="19" y2="14"/><line x1="22" y1="11" x2="16" y2="11"/></svg></span><span class="rail-label">Doctors</span></a>
            <a href="admin_schedules.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="17" rx="3"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg></span><span class="rail-label">Schedules</span></a>
            <a href="admin_laboratory.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 2v6.3L4.5 17a2.5 2.5 0 0 0 2 4h11a2.5 2.5 0 0 0 2-4L14 8.3V2"/><path d="M8.5 2h7"/><path d="M7 15h10"/></svg></span><span class="rail-label">Laboratory</span></a>
            <a href="admin_vitals.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg></span><span class="rail-label">Vitals &amp; Vaccines</span></a>
            <a href="admin_reports.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v18h18"/><path d="M7 15v-4"/><path d="M12 15V7"/><path d="M17 15v-6"/></svg></span><span class="rail-label">Reports</span></a>
            <a href="admin_history.php" class="nav-item"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="4" rx="1"/><path d="M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/></svg></span><span class="rail-label">Archives</span></a>
        </nav>
        <div class="sidebar-footer">
            <a href="admin_logout.php" class="btn-logout" data-tip="Sign Out"><span class="nav-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg></span><span class="rail-label">Sign Out</span></a>
        </div>
    </aside>

        <main class="admin-content">
            <header class="topbar">
                <div class="topbar-left">
                    <button class="mobile-menu-btn" onclick="toggleSidebar()" aria-label="Open menu"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button>
                    <span class="topbar-title">Doctors</span>
                </div>
                <div class="topbar-actions">
    <button type="button" class="theme-toggle" title="Toggle dark mode" aria-label="Toggle dark mode"><svg class="theme-icon theme-icon--sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M19.07 4.93l-1.41 1.41M6.34 17.66l-1.41 1.41"/></svg><svg class="theme-icon theme-icon--moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg></button>
                    <div class="topbar-hello"><span class="topbar-hello-label">Hello,</span><strong><?php echo htmlspecialchars(explode(' ', trim($admin_name))[0]); ?></strong></div>
                    <div class="avatar avatar--topbar"><?php echo strtoupper(substr(trim($admin_name),0,1)); ?></div>
                </div>
            </header>

            <div class="content-card">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1.25rem;flex-wrap:wrap;gap:0.75rem;">
                    <h2 style="margin-bottom:0;">All Doctors</h2>
                    <button class="btn-add" onclick="openAddModal()"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg> Add Doctor</button>
                </div>

                <div class="doctors-grid">
                    <?php while ($doctor = $doctors->fetch_assoc()): ?>
                    <div class="doctor-card">
                        <h3>Dr. <?php echo htmlspecialchars($doctor['name']); ?></h3>
                        <div class="doctor-specialty"><?php echo htmlspecialchars($doctor['specialty']); ?></div>
                        <div class="doctor-meta"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="17" rx="3"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg><?php echo htmlspecialchars($doctor['schedule']); ?></div>
                        <div class="doctor-meta"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg><?php echo (int)$doctor['experience']; ?> years experience</div>
                        <div class="doctor-footer">
                            <span>Appointments: <span style="color:#16a34a"><?php echo $doctor['appointment_count']; ?></span></span>
                        </div>
<div class="doctor-actions">
                            <button class="btn-sm btn-edit"
                                data-id="<?php echo $doctor['id']; ?>"
                                data-name="<?php echo htmlspecialchars($doctor['name'], ENT_QUOTES); ?>"
                                data-specialty="<?php echo htmlspecialchars($doctor['specialty'], ENT_QUOTES); ?>"
                                data-schedule="<?php echo htmlspecialchars($doctor['schedule'], ENT_QUOTES); ?>"
                                data-experience="<?php echo (int)$doctor['experience']; ?>"
                                onclick="openEditModal(this)"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"/></svg> Edit</button>
                            <button class="btn-sm btn-delete"
                                data-id="<?php echo $doctor['id']; ?>"
                                data-name="<?php echo htmlspecialchars($doctor['name'], ENT_QUOTES); ?>"
                                onclick="confirmDelete(this)"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg> Delete</button>
                        </div>
                    </div>
                    <?php endwhile; ?>
</div>
            </div>

            <!-- == Doctor Accounts == -->
            <div class="content-card">
                <h2 style="margin-bottom:0.5rem;">Doctor Login Accounts</h2>
                <p style="color:#64748b;margin:0 0 1.25rem;font-size:0.93rem;">
                    Doctor accounts let doctors log into their own portal to enter lab results and set their availability.
                </p>

                <div style="background:var(--off-white);border:1px solid var(--gray-100);border-radius:14px;padding:1.1rem 1.25rem;margin-bottom:1.6rem;">
                    <h3 style="margin-bottom:0.9rem;font-size:1rem;">Create New Account</h3>
                    <form id="addAccountForm" novalidate>
                        <div class="form-grid">
                            <div class="form-group">
                                <label for="acctDoctor">Doctor</label>
                                <select name="doctor_id" id="acctDoctor" class="form-dropdown" required>
                                    <option value="">Select Doctor</option>
                                    <?php $doctors_options->data_seek(0); while ($doc = $doctors_options->fetch_assoc()): ?>
                                    <option value="<?php echo $doc['id']; ?>">Dr. <?php echo htmlspecialchars($doc['name']); ?> &mdash; <?php echo htmlspecialchars($doc['specialty']); ?></option>
                                    <?php endwhile; ?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="acctUsername">Username</label>
                                <input type="text" name="username" id="acctUsername" placeholder="e.g. dr_dela_cruz" maxlength="30" required>
                            </div>
                            <div class="form-group">
                                <label for="acctPassword">Password</label>
                                <input type="password" name="password" id="acctPassword" placeholder="At least 8 characters" minlength="8" required>
                            </div>
                            <div class="form-group" style="display:flex;align-items:flex-end;">
                                <button type="submit" class="btn-primary"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg> Create Account</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="table-scroll">
                    <table>
                        <thead><tr><th>Doctor</th><th>Specialty</th><th>Username</th><th>Created</th><th>Action</th></tr></thead>
                        <tbody>
                        <?php if ($accounts && $accounts->num_rows > 0): ?>
                            <?php while ($ac = $accounts->fetch_assoc()): ?>
                            <tr>
                                <td><strong>Dr. <?php echo htmlspecialchars($ac['doctor_name']); ?></strong></td>
                                <td><?php echo htmlspecialchars($ac['specialty']); ?></td>
                                <td><code style="background:var(--off-white);padding:.2rem .5rem;border-radius:6px;"><?php echo htmlspecialchars($ac['username']); ?></code></td>
                                <td><?php echo date('M j, Y', strtotime($ac['created_at'])); ?></td>
                                <td style="white-space:nowrap">
                                    <button class="btn-sm btn-edit" onclick="openResetModal(<?php echo $ac['account_id']; ?>, '<?php echo addslashes(htmlspecialchars($ac['doctor_name'], ENT_QUOTES)); ?>')"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"/></svg> Reset Password</button>
                                    <button class="btn-sm btn-delete" onclick="confirmAccountDelete(<?php echo $ac['account_id']; ?>)"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button>
                                </td>
                            </tr>
                            <?php endwhile; ?>
                        <?php else: ?>
                            <tr><td colspan="5" class="empty-state-row"><div class="empty-icon"><svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div>No doctor accounts yet. Create one above.</td></tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </main>
    </div>

    <!-- Reset Password Modal -->
    <div class="modal-overlay" id="resetAccountModal">
        <div class="modal-box">
            <button class="modal-close-btn" onclick="closeModal('resetAccountModal')">&times;</button>
            <h2>Reset Password</h2>
            <p id="resetAcctMsg" style="color:#64748b;margin-bottom:1.25rem;font-size:0.95rem;"></p>
            <form id="resetAccountForm" novalidate>
                <input type="hidden" name="account_id" id="resetAccountId">
                <div class="form-group">
                    <label for="resetPassword">New Password</label>
                    <input type="password" name="password" id="resetPassword" placeholder="At least 8 characters" minlength="8" required>
                </div>
                <div class="form-actions">
                    <button type="button" class="btn-secondary" onclick="closeModal('resetAccountModal')">Cancel</button>
                    <button type="submit" class="btn-primary">Save New Password</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Delete Account Confirm Modal -->
    <div class="modal-overlay" id="deleteAccountModal">
        <div class="modal-box" style="max-width:400px;text-align:center;">
            <button class="modal-close-btn" onclick="closeModal('deleteAccountModal')">&times;</button>
            <div style="font-size:3rem;margin-bottom:0.75rem;color:#16a34a;display:flex;justify-content:center;"><svg width="46" height="46" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></div>
            <h2 style="margin-bottom:0.5rem;">Delete Account?</h2>
            <p style="color:#64748b;margin-bottom:1.5rem;font-size:0.95rem;">This removes the doctor's login access. The doctor profile will be kept.</p>
            <input type="hidden" id="deleteAccountId">
            <div class="form-actions" style="justify-content:center;">
                <button class="btn-secondary" onclick="closeModal('deleteAccountModal')">Cancel</button>
                <button class="btn-sm btn-delete" style="padding:0.65rem 1.25rem;font-size:0.95rem;" onclick="executeAccountDelete()">Yes, Delete</button>
            </div>
        </div>
    </div>

    <!-- Add Doctor Modal -->
    <div class="modal-overlay" id="addModal">
        <div class="modal-box">
            <button class="modal-close-btn" onclick="closeModal('addModal')">&times;</button>
            <h2>Add New Doctor</h2>
            <form id="addForm">
                <div class="form-grid">
                    <div class="form-group">
                        <label>Full Name</label>
                        <input type="text" name="name" placeholder="e.g. Juan dela Cruz" required>
                    </div>
                    <div class="form-group">
                        <label>Specialty</label>
                        <input type="text" name="specialty" placeholder="e.g. Obstetrics & Gynecology" required>
                    </div>
                    <div class="form-group">
                        <label>Schedule</label>
                        <input type="text" name="schedule" placeholder="e.g. Mon-Fri: 9AM-5PM" required>
                    </div>
                    <div class="form-group">
                        <label>Years of Experience</label>
                        <input type="number" name="experience" placeholder="e.g. 10" min="0" max="60" required>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="button" class="btn-secondary" onclick="closeModal('addModal')">Cancel</button>
                    <button type="submit" class="btn-primary">Save Doctor</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Edit Doctor Modal -->
    <div class="modal-overlay" id="editModal">
        <div class="modal-box">
            <button class="modal-close-btn" onclick="closeModal('editModal')">&times;</button>
            <h2>Edit Doctor</h2>
            <form id="editForm">
                <input type="hidden" name="doctor_id" id="editDoctorId">
                <div class="form-grid">
                    <div class="form-group">
                        <label>Full Name</label>
                        <input type="text" name="name" id="editName" required>
                    </div>
                    <div class="form-group">
                        <label>Specialty</label>
                        <input type="text" name="specialty" id="editSpecialty" required>
                    </div>
                    <div class="form-group">
                        <label>Schedule</label>
                        <input type="text" name="schedule" id="editSchedule" required>
                    </div>
                    <div class="form-group">
                        <label>Years of Experience</label>
                        <input type="number" name="experience" id="editExperience" min="0" max="60" required>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="button" class="btn-secondary" onclick="closeModal('editModal')">Cancel</button>
                    <button type="submit" class="btn-primary">Update Doctor</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Delete Confirm Modal -->
    <div class="modal-overlay" id="deleteModal">
        <div class="modal-box" style="max-width:400px;text-align:center;">
            <button class="modal-close-btn" onclick="closeModal('deleteModal')">&times;</button>
            <div style="font-size:3rem;margin-bottom:0.75rem;color:#16a34a;display:flex;justify-content:center;"><svg width="46" height="46" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></div>
            <h2 style="margin-bottom:0.5rem;">Delete Doctor?</h2>
            <p id="deleteModalMsg" style="color:#64748b;margin-bottom:1.5rem;font-size:0.95rem;"></p>
            <input type="hidden" id="deleteDoctorId">
            <div class="form-actions" style="justify-content:center;">
                <button class="btn-secondary" onclick="closeModal('deleteModal')">Cancel</button>
                <button class="btn-sm btn-delete" style="padding:0.65rem 1.25rem;font-size:0.95rem;" onclick="executeDelete()">Yes, Delete</button>
            </div>
        </div>
    </div>

    <div id="loadingScreen" class="loading-screen"><div class="spinner"></div><p>Processing...</p></div>
    <div id="toast" class="toast"></div>

    <script>
        function openSidebar(){document.getElementById('adminSidebar').classList.add('open');document.getElementById('sidebarOverlay').classList.add('active');document.body.style.overflow='hidden';}
        function closeSidebar(){document.getElementById('adminSidebar').classList.remove('open');document.getElementById('sidebarOverlay').classList.remove('active');document.body.style.overflow='';}
        function toggleSidebar(){
          var sb=document.getElementById('adminSidebar');
          if(sb.classList.contains('open')){
            sb.classList.remove('open');
            document.getElementById('sidebarOverlay').classList.remove('active');
            document.body.style.overflow='';
          }else{
            sb.classList.add('open');
            if(window.matchMedia('(max-width: 900px)').matches){
              document.getElementById('sidebarOverlay').classList.add('active');
              document.body.style.overflow='hidden';
            }
          }
        }
        function showToast(msg,type=''){const t=document.getElementById('toast');t.textContent=msg;t.className='toast show'+(type?' '+type:'');setTimeout(()=>t.className='toast',3000);}
        function showLoading(){document.getElementById('loadingScreen').classList.add('active');}
        function hideLoading(){document.getElementById('loadingScreen').classList.remove('active');}
        function openModal(id){document.getElementById(id).classList.add('active');}
        function closeModal(id){document.getElementById(id).classList.remove('active');}

        document.querySelectorAll('.modal-overlay').forEach(overlay => {
            overlay.addEventListener('click', function(e){
                if(e.target === this) closeModal(this.id);
            });
        });

        // -- Add ----------------------------------------------
        function openAddModal(){
            document.getElementById('addForm').reset();
            openModal('addModal');
        }

        document.getElementById('addForm').addEventListener('submit', function(e){
            e.preventDefault();
            showLoading();
            const fd = new FormData(this);
            fd.append('action', 'add');
            fetch('admin_doctor_actions.php', {method:'POST', body:fd})
                .then(r => { if(!r.ok) throw new Error('HTTP ' + r.status + ' ' + r.statusText); return r.text(); })
                .then(res => {
                    hideLoading();
                    if(res.trim() === 'success'){
                        showToast('Doctor added successfully!', 'success');
                        closeModal('addModal');
                        document.body.classList.add('__leaving');setTimeout(()=>location.reload(),215);
                    } else { showToast(res.trim(), 'error'); }
                })
                .catch(err => { hideLoading(); showToast('Error: ' + err.message, 'error'); });
        });

        // -- Edit ---------------------------------------------
        function openEditModal(btn){
            document.getElementById('editDoctorId').value    = btn.dataset.id;
            document.getElementById('editName').value        = btn.dataset.name;
            document.getElementById('editSpecialty').value   = btn.dataset.specialty;
            document.getElementById('editSchedule').value    = btn.dataset.schedule;
            document.getElementById('editExperience').value  = btn.dataset.experience;
            openModal('editModal');
        }

        document.getElementById('editForm').addEventListener('submit', function(e){
            e.preventDefault();
            showLoading();
            const fd = new FormData(this);
            fd.append('action', 'edit');
            fetch('admin_doctor_actions.php', {method:'POST', body:fd})
                .then(r => { if(!r.ok) throw new Error('HTTP ' + r.status + ' ' + r.statusText); return r.text(); })
                .then(res => {
                    hideLoading();
                    if(res.trim() === 'success'){
                        showToast('Doctor updated successfully!', 'success');
                        closeModal('editModal');
                        document.body.classList.add('__leaving');setTimeout(()=>location.reload(),215);
                    } else { showToast(res.trim(), 'error'); }
                })
                .catch(err => { hideLoading(); showToast('Error: ' + err.message, 'error'); });
        });

        // -- Delete -------------------------------------------
        function confirmDelete(btn){
            document.getElementById('deleteDoctorId').value = btn.dataset.id;
            document.getElementById('deleteModalMsg').textContent =
                'Are you sure you want to delete Dr. ' + btn.dataset.name + '? This action cannot be undone.';
            openModal('deleteModal');
        }

        function executeDelete(){
            const id = document.getElementById('deleteDoctorId').value;
            showLoading();
            const fd = new FormData();
            fd.append('action', 'delete');
            fd.append('doctor_id', id);
            fetch('admin_doctor_actions.php', {method:'POST', body:fd})
                .then(r => { if(!r.ok) throw new Error('HTTP ' + r.status + ' ' + r.statusText); return r.text(); })
                .then(res => {
                    hideLoading();
                    if(res.trim() === 'success'){
                        showToast('Doctor deleted!', 'success');
                        closeModal('deleteModal');
                        document.body.classList.add('__leaving');setTimeout(()=>location.reload(),215);
                    } else { showToast(res.trim(), 'error'); }
                })
                .catch(err => { hideLoading(); showToast('Error: ' + err.message, 'error'); });
}

    /* -- Doctor Accounts -- */
    document.getElementById('addAccountForm').addEventListener('submit', function(e){
        e.preventDefault();
        const doctorSel = document.getElementById('acctDoctor');
        const usr = document.getElementById('acctUsername').value.trim();
        const pwd = document.getElementById('acctPassword').value;
        if (!doctorSel.value) { showToast('Please select a doctor', 'error'); return; }
        if (!/^[a-zA-Z0-9_]{3,30}$/.test(usr)) { showToast('Username must be 3-30 characters (letters, numbers, underscore only)', 'error'); return; }
        if (pwd.length < 8) { showToast('Password must be at least 8 characters', 'error'); return; }
        showLoading();
        const fd = new FormData(this);
        fd.append('action', 'add_account');
        fetch('admin_doctor_actions.php', {method:'POST', body:fd})
            .then(r => r.text())
            .then(res => {
                hideLoading();
                if(res.trim() === 'success'){
                    showToast('Doctor account created!','success');
                    document.body.classList.add('__leaving');setTimeout(()=>location.reload(),215);
                } else { showToast(res.trim(), 'error'); }
            })
            .catch(() => { hideLoading(); showToast('Network error','error'); });
    });

    function openResetModal(id, doctorName){
        document.getElementById('resetAccountId').value = id;
        document.getElementById('resetAcctMsg').textContent = 'Set a new password for Dr. ' + doctorName + '.';
        document.getElementById('resetAccountForm').reset();
        document.getElementById('resetPassword').value = '';
        openModal('resetAccountModal');
    }
    document.getElementById('resetAccountForm').addEventListener('submit', function(e){
        e.preventDefault();
        if (document.getElementById('resetPassword').value.length < 8) { showToast('Password must be at least 8 characters', 'error'); return; }
        showLoading();
        const fd = new FormData(this);
        fd.append('action', 'reset_account');
        fetch('admin_doctor_actions.php', {method:'POST', body:fd})
            .then(r => r.text())
            .then(res => {
                hideLoading();
                if(res.trim() === 'success'){
                    showToast('Password reset!','success');
                    closeModal('resetAccountModal');
                    document.body.classList.add('__leaving');setTimeout(()=>location.reload(),215);
                } else { showToast(res.trim(), 'error'); }
            })
            .catch(() => { hideLoading(); showToast('Network error','error'); });
    });

    function confirmAccountDelete(id){
        document.getElementById('deleteAccountId').value = id;
        openModal('deleteAccountModal');
    }
    function executeAccountDelete(){
        const id = document.getElementById('deleteAccountId').value;
        showLoading();
        const fd = new FormData();
        fd.append('action', 'delete_account');
        fd.append('account_id', id);
        fetch('admin_doctor_actions.php', {method:'POST', body:fd})
            .then(r => r.text())
            .then(res => {
                hideLoading();
                if(res.trim() === 'success'){
                    showToast('Doctor account deleted!','success');
                    closeModal('deleteAccountModal');
                    document.body.classList.add('__leaving');setTimeout(()=>location.reload(),215);
                } else { showToast(res.trim(), 'error'); }
            })
            .catch(() => { hideLoading(); showToast('Network error','error'); });
    }

    /* -- LustreMDC Smooth Transitions -- */
    (function(){
      const s=document.createElement('style');
      s.textContent=`
        @keyframes __meIn  {from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
        @keyframes __meOut {from{opacity:1;transform:translateY(0)}to{opacity:0;transform:translateY(-6px)}}
        @keyframes __meFade {from{opacity:0}to{opacity:1}}
        @keyframes __meFadeOut {from{opacity:1}to{opacity:0}}
        body{animation:__meFade .4s ease both}
        body.__leaving{animation:__meFadeOut .22s ease forwards;pointer-events:none}
        button:not(:disabled):active{transform:scale(.965) !important}
        .content-card{animation:__meIn .42s cubic-bezier(.22,1,.36,1) both}
        .stat-card{animation:__meIn .38s cubic-bezier(.22,1,.36,1) both}
        tr{transition:background .15s}
        .modal-box{animation:__meIn .3s cubic-bezier(.34,1.56,.64,1)}
        .result-modal-box{animation:__meIn .3s cubic-bezier(.34,1.56,.64,1)}
        .doctor-card{transition:transform .2s,box-shadow .22s !important}
        .doctor-card:hover{transform:translateY(-3px) !important}
        .stat-card{opacity:0;animation:__meIn .38s cubic-bezier(.22,1,.36,1) both;animation-fill-mode:both}
        .content-card{animation:__meIn .42s cubic-bezier(.22,1,.36,1) both;animation-delay:.1s;opacity:0;animation-fill-mode:both}
        .doctor-card{transition:transform .2s,box-shadow .22s,border-color .2s !important;opacity:0;animation:__meIn .35s cubic-bezier(.22,1,.36,1) both;animation-fill-mode:both}
        .doctors-grid .doctor-card:nth-child(1){animation-delay:.06s}
        .doctors-grid .doctor-card:nth-child(2){animation-delay:.11s}
        .doctors-grid .doctor-card:nth-child(3){animation-delay:.16s}
        .doctors-grid .doctor-card:nth-child(4){animation-delay:.21s}
        .doctors-grid .doctor-card:nth-child(5){animation-delay:.26s}
        .doctors-grid .doctor-card:nth-child(6){animation-delay:.31s}
        .doctor-card:hover{transform:translateY(-4px) !important;box-shadow:0 8px 24px rgba(22,163,74,.18) !important}
        .modal-box{animation:__meIn .3s cubic-bezier(.34,1.56,.64,1)}
      `;
      document.head.appendChild(s);
      document.addEventListener('click',function(e){
        const link=e.target.closest('a[href]');
        if(!link)return;
        const href=link.getAttribute('href');
        if(!href||href.startsWith('#')||href.startsWith('javascript')||href.startsWith('http')||link.getAttribute('target')==='_blank')return;
        e.preventDefault();
        document.body.classList.add('__leaving');
        setTimeout(()=>{window.location.href=href;},215);
      });
    })();
</script>
<script src="admin_components.js?v=<?= filemtime(__DIR__ . '/../admin_components.js') ?>"></script>
<script src="admin_theme.js?v=<?= filemtime(__DIR__ . '/../admin_theme.js') ?>"></script>
</body>
</html>