<?php
require __DIR__ . '/../toddcare-backend/src/session.php';
include __DIR__ . '/../toddcare-backend/src/db.php';

// Ensure the email_tokens table exists
$conn->query("CREATE TABLE IF NOT EXISTS email_tokens (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    token      VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used       SMALLINT     NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
)");

header('Content-Type: text/plain; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo "Invalid request";
    exit;
}

$email = isset($_POST['email']) ? trim($_POST['email']) : '';
if (empty($email) || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    echo "Please enter a valid email address";
    exit;
}

// Verify the email belongs to a registered patient (hide existence for accounts â€” but
// show a friendly message here since this is the account owner's own request)
$stmt = $conn->prepare("SELECT id, name FROM patients WHERE email = ?");
$stmt->bind_param("s", $email);
$stmt->execute();
$stmt->store_result();

if ($stmt->num_rows === 0) {
    $stmt->close();
    echo "No account found with that email address";
    exit;
}

$stmt->bind_result($pid, $name);
$stmt->fetch();
$stmt->close();

// Stage the reset in the session
$_SESSION['pwd_reset'] = array(
    'email'        => $email,
    'otp_attempts' => 0,
    'verified'     => false
);

// ---- Generate and store the OTP ----
$otp = str_pad((string)random_int(0, 999999), 6, '0', STR_PAD_LEFT);
$token_hash = hash('sha256', $otp);
$expires = date('Y-m-d H:i:s', time() + (15 * 60));

// Rotate any unused tokens for this email
$conn->prepare("UPDATE email_tokens SET used = 1 WHERE email = ? AND used = 0")->execute([$email]);

$stmt = $conn->prepare("INSERT INTO email_tokens (email, token, expires_at, used) VALUES (?, ?, ?, 0)");
$stmt->bind_param("sss", $email, $token_hash, $expires);
if (!$stmt->execute()) {
    $stmt->close();
    echo "Failed to save verification code. Please try again.";
    exit;
}
$stmt->close();

// ---- Send the OTP email ----
$subject = 'LustreMDC â€” Password Reset Code';
$message = "Hello " . $name . ",\n\n"
    . "We received a request to reset the password for your LustreMDC account.\n\n"
    . "Your password reset code is: " . $otp . "\n\n"
    . "This code will expire in 15 minutes.\n"
    . "If you did not request this, you can safely ignore this email.\n\n"
    . "â€” LustreMDC Clinics & Diagnostics";

require __DIR__ . '/../toddcare-backend/src/SMTPMailer.php';

try {
    $mail = new SMTPMailer();
    $mail->send($email, $subject, $message, $name);
    echo "success";
} catch (Exception $e) {
    unset($_SESSION['pwd_reset']);
    error_log("SMTP failed: " . $e->getMessage());
    echo "Failed to send the verification email. Please check your server email configuration and try again.";
}

$conn->close();
?>