<?php
require __DIR__ . '/../toddcare-backend/src/session.php';
include __DIR__ . '/../toddcare-backend/src/db.php';

// Ensure the email_tokens table exists
$conn->query("CREATE TABLE IF NOT EXISTS email_tokens (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    token      VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    used       SMALLINT     NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
)");

header('Content-Type: text/plain; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo "Invalid request";
    exit;
}

// ---- Validate all registration fields (same rules as register.php) ----
$name     = isset($_POST['name']) ? trim($_POST['name']) : '';
$email    = isset($_POST['email']) ? trim($_POST['email']) : '';
$contact  = isset($_POST['contact']) ? trim($_POST['contact']) : '';
$address  = isset($_POST['address']) ? trim($_POST['address']) : '';
$password = isset($_POST['password']) ? trim($_POST['password']) : '';
$birthday = isset($_POST['birthday']) ? trim($_POST['birthday']) : '';
$age      = isset($_POST['age']) ? trim($_POST['age']) : '';
$gender   = isset($_POST['gender']) ? strtolower(trim($_POST['gender'])) : '';

if (empty($name) || empty($email) || empty($contact) || empty($address) || empty($password)) {
    echo "All fields are required";
    exit;
}

if (!in_array($gender, ['male', 'female'], true)) {
    echo "Please choose a valid gender";
    exit;
}

if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    echo "Invalid email format";
    exit;
}

if (strlen($password) < 8 || !preg_match('/[A-Z]/', $password) || !preg_match('/[a-z]/', $password) || !preg_match('/[0-9]/', $password)) {
    echo "Password must be at least 8 characters and include uppercase, lowercase, and a number";
    exit;
}

// Check if email already exists
$stmt = $conn->prepare("SELECT id FROM patients WHERE email = ?");
$stmt->bind_param("s", $email);
$stmt->execute();
$stmt->store_result();

if ($stmt->num_rows > 0) {
    $stmt->close();
    echo "Email already registered";
    exit;
}
$stmt->close();

// ---- Stage the registration data in the session for register_otp_verify step ----
$_SESSION['reg_pending'] = array(
    'name'     => $name,
    'email'    => $email,
    'contact'  => $contact,
    'address'  => $address,
    'password' => $password,
    'birthday' => $birthday,
    'age'      => $age,
    'gender'   => $gender,
    'otp_attempts' => 0
);

// ---- Generate and store the OTP ----
$otp = str_pad((string)random_int(0, 999999), 6, '0', STR_PAD_LEFT);
$token_hash = hash('sha256', $otp);
$expires = date('Y-m-d H:i:s', time() + (15 * 60));

// Rotate any unused tokens for this email
$conn->prepare("UPDATE email_tokens SET used = 1 WHERE email = ? AND used = 0")->execute([$email]);

$stmt = $conn->prepare("INSERT INTO email_tokens (email, token, expires_at, used) VALUES (?, ?, ?, 0)");
$stmt->bind_param("sss", $email, $token_hash, $expires);
if (!$stmt->execute()) {
    $stmt->close();
    echo "Failed to save verification code. Please try again.";
    exit;
}
$stmt->close();

// ---- Send the OTP email ----
$subject = 'LustreMDC â€” Verify Your Email';
$full_name = $name;
$message = "Hello " . $full_name . ",\n\n"
    . "Thank you for registering with LustreMDC Clinics & Diagnostics.\n\n"
    . "Your email verification code is: " . $otp . "\n\n"
    . "This code will expire in 15 minutes.\n"
    . "If you did not sign up for an account, you can ignore this email.\n\n"
    . "â€” LustreMDC Clinics & Diagnostics";

require __DIR__ . '/../toddcare-backend/src/SMTPMailer.php';

try {
    $mail = new SMTPMailer();
    $mail->send($email, $subject, $message, $full_name);
    echo "success";
} catch (Exception $e) {
    unset($_SESSION['reg_pending']);
    error_log("SMTP failed: " . $e->getMessage());
    echo "Failed to send the verification email. Please check your server email configuration and try again.";
}

$conn->close();
?>